In [148]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import optimizers

In [149]:
x_train = np.genfromtxt('train.in', dtype=np.float32)

In [150]:
y_train = np.genfromtxt('train.out', dtype=np.float32)

In [151]:
x_test = np.genfromtxt('result.in', dtype=np.float32)

In [152]:
y_test = np.genfromtxt('result.out', dtype=np.float32)

In [153]:
x_train.reshape(-1, 1)

array([[75.],
       [89.],
       [43.],
       ...,
       [87.],
       [41.],
       [14.]], dtype=float32)

In [154]:
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [155]:
y_train

array([[1.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [1.]], dtype=float32)

In [156]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units = 1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('sigmoid'))  # this line can be omitted, as linear activation is default
tf.model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [157]:
history = tf.model.fit(x_train, y_train, epochs=100)
tf.model.summary()

Epoch 1/100
313/313 [==============================] - 0s 451us/step - loss: 4.7710 - accuracy: 0.5357
Epoch 2/100
313/313 [==============================] - 0s 447us/step - loss: 1.2665 - accuracy: 0.5647
Epoch 3/100
313/313 [==============================] - 0s 447us/step - loss: 0.6160 - accuracy: 0.5996
Epoch 4/100
313/313 [==============================] - 0s 448us/step - loss: 0.5959 - accuracy: 0.6481
Epoch 5/100
313/313 [==============================] - 0s 452us/step - loss: 0.5774 - accuracy: 0.6977
Epoch 6/100
313/313 [==============================] - 0s 443us/step - loss: 0.5574 - accuracy: 0.7350
Epoch 7/100
313/313 [==============================] - 0s 447us/step - loss: 0.5421 - accuracy: 0.7615
Epoch 8/100
313/313 [==============================] - 0s 438us/step - loss: 0.5249 - accuracy: 0.7895
Epoch 9/100
313/313 [==============================] - 0s 451us/step - loss: 0.5093 - accuracy: 0.8050
Epoch 10/100
313/313 [==============================] - 0s 441us/step - l

In [158]:
y_predict = tf.model.predict(x_test)
y_predict = tf.cast(y_predict >= 0.5, dtype=tf.float32)

In [159]:
print((y_predict.numpy() == y_test).all())

False


In [160]:
print(y_predict.numpy())

[[1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.

In [161]:
meval_test = tf.model.evaluate(x_test, y_test)
print(meval_test) 

32/32 [==============================] - 0s 404us/step - loss: 1.6980 - accuracy: 0.5070
[1.6980394124984741, 0.5070000290870667]


In [162]:
meval = tf.model.evaluate(x_train, y_train)
print(meval) 

313/313 [==============================] - 0s 385us/step - loss: 0.1582 - accuracy: 0.9891
[0.15815144777297974, 0.9890999794006348]
