In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
print(a + a)

[ 2  4  6  8 10]


In [5]:
a = np.array([[1, 2], [3, 4]])

In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
b = np.array([[1], [2], [3], [4]])

In [8]:
print(a)

[1 2 3 4]


In [9]:
print(b)

[[1]
 [2]
 [3]
 [4]]


In [10]:
np.multiply(a, b)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [11]:
np.matmul(a,b)

array([30])

In [12]:
np.multiply(b, a)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [13]:
np.dot(a, b)

array([30])

In [14]:
a = np.array([[1], [2], [3], [4]])

In [15]:
print(a)

[[1]
 [2]
 [3]
 [4]]


In [16]:
print(a.T)

[[1 2 3 4]]


In [17]:
a = np.array([1, 2, 3, 4])

In [18]:
print(a)

[1 2 3 4]


In [19]:
print(a.T)

[1 2 3 4]
